name: solid_api_sample

services:
    solid_api_mysql:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: docker123
            MYSQL_DATABASE: gympass-db
