
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmailChange` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmailChange
 * 
 */
export type EmailChangeModel = runtime.Types.Result.DefaultSelection<Prisma.$EmailChangePayload>

export type AggregateEmailChange = {
  _count: EmailChangeCountAggregateOutputType | null
  _avg: EmailChangeAvgAggregateOutputType | null
  _sum: EmailChangeSumAggregateOutputType | null
  _min: EmailChangeMinAggregateOutputType | null
  _max: EmailChangeMaxAggregateOutputType | null
}

export type EmailChangeAvgAggregateOutputType = {
  attempts: number | null
}

export type EmailChangeSumAggregateOutputType = {
  attempts: number | null
}

export type EmailChangeMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  new_email: string | null
  link_token: string | null
  otp_code: string | null
  attempts: number | null
  expires_at: Date | null
  used_at: Date | null
  created_at: Date | null
}

export type EmailChangeMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  new_email: string | null
  link_token: string | null
  otp_code: string | null
  attempts: number | null
  expires_at: Date | null
  used_at: Date | null
  created_at: Date | null
}

export type EmailChangeCountAggregateOutputType = {
  id: number
  user_id: number
  new_email: number
  link_token: number
  otp_code: number
  attempts: number
  expires_at: number
  used_at: number
  created_at: number
  _all: number
}


export type EmailChangeAvgAggregateInputType = {
  attempts?: true
}

export type EmailChangeSumAggregateInputType = {
  attempts?: true
}

export type EmailChangeMinAggregateInputType = {
  id?: true
  user_id?: true
  new_email?: true
  link_token?: true
  otp_code?: true
  attempts?: true
  expires_at?: true
  used_at?: true
  created_at?: true
}

export type EmailChangeMaxAggregateInputType = {
  id?: true
  user_id?: true
  new_email?: true
  link_token?: true
  otp_code?: true
  attempts?: true
  expires_at?: true
  used_at?: true
  created_at?: true
}

export type EmailChangeCountAggregateInputType = {
  id?: true
  user_id?: true
  new_email?: true
  link_token?: true
  otp_code?: true
  attempts?: true
  expires_at?: true
  used_at?: true
  created_at?: true
  _all?: true
}

export type EmailChangeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailChange to aggregate.
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailChanges to fetch.
   */
  orderBy?: Prisma.EmailChangeOrderByWithRelationInput | Prisma.EmailChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmailChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmailChanges
  **/
  _count?: true | EmailChangeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmailChangeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmailChangeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmailChangeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmailChangeMaxAggregateInputType
}

export type GetEmailChangeAggregateType<T extends EmailChangeAggregateArgs> = {
      [P in keyof T & keyof AggregateEmailChange]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmailChange[P]>
    : Prisma.GetScalarType<T[P], AggregateEmailChange[P]>
}




export type EmailChangeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailChangeWhereInput
  orderBy?: Prisma.EmailChangeOrderByWithAggregationInput | Prisma.EmailChangeOrderByWithAggregationInput[]
  by: Prisma.EmailChangeScalarFieldEnum[] | Prisma.EmailChangeScalarFieldEnum
  having?: Prisma.EmailChangeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmailChangeCountAggregateInputType | true
  _avg?: EmailChangeAvgAggregateInputType
  _sum?: EmailChangeSumAggregateInputType
  _min?: EmailChangeMinAggregateInputType
  _max?: EmailChangeMaxAggregateInputType
}

export type EmailChangeGroupByOutputType = {
  id: string
  user_id: string
  new_email: string
  link_token: string
  otp_code: string
  attempts: number
  expires_at: Date
  used_at: Date | null
  created_at: Date
  _count: EmailChangeCountAggregateOutputType | null
  _avg: EmailChangeAvgAggregateOutputType | null
  _sum: EmailChangeSumAggregateOutputType | null
  _min: EmailChangeMinAggregateOutputType | null
  _max: EmailChangeMaxAggregateOutputType | null
}

export type GetEmailChangeGroupByPayload<T extends EmailChangeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmailChangeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmailChangeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmailChangeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmailChangeGroupByOutputType[P]>
      }
    >
  >



export type EmailChangeWhereInput = {
  AND?: Prisma.EmailChangeWhereInput | Prisma.EmailChangeWhereInput[]
  OR?: Prisma.EmailChangeWhereInput[]
  NOT?: Prisma.EmailChangeWhereInput | Prisma.EmailChangeWhereInput[]
  id?: Prisma.StringFilter<"EmailChange"> | string
  user_id?: Prisma.StringFilter<"EmailChange"> | string
  new_email?: Prisma.StringFilter<"EmailChange"> | string
  link_token?: Prisma.StringFilter<"EmailChange"> | string
  otp_code?: Prisma.StringFilter<"EmailChange"> | string
  attempts?: Prisma.IntFilter<"EmailChange"> | number
  expires_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
  used_at?: Prisma.DateTimeNullableFilter<"EmailChange"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type EmailChangeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  new_email?: Prisma.SortOrder
  link_token?: Prisma.SortOrder
  otp_code?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  used_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.EmailChangeOrderByRelevanceInput
}

export type EmailChangeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  link_token?: string
  AND?: Prisma.EmailChangeWhereInput | Prisma.EmailChangeWhereInput[]
  OR?: Prisma.EmailChangeWhereInput[]
  NOT?: Prisma.EmailChangeWhereInput | Prisma.EmailChangeWhereInput[]
  user_id?: Prisma.StringFilter<"EmailChange"> | string
  new_email?: Prisma.StringFilter<"EmailChange"> | string
  otp_code?: Prisma.StringFilter<"EmailChange"> | string
  attempts?: Prisma.IntFilter<"EmailChange"> | number
  expires_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
  used_at?: Prisma.DateTimeNullableFilter<"EmailChange"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "link_token">

export type EmailChangeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  new_email?: Prisma.SortOrder
  link_token?: Prisma.SortOrder
  otp_code?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  used_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.EmailChangeCountOrderByAggregateInput
  _avg?: Prisma.EmailChangeAvgOrderByAggregateInput
  _max?: Prisma.EmailChangeMaxOrderByAggregateInput
  _min?: Prisma.EmailChangeMinOrderByAggregateInput
  _sum?: Prisma.EmailChangeSumOrderByAggregateInput
}

export type EmailChangeScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmailChangeScalarWhereWithAggregatesInput | Prisma.EmailChangeScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmailChangeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmailChangeScalarWhereWithAggregatesInput | Prisma.EmailChangeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmailChange"> | string
  user_id?: Prisma.StringWithAggregatesFilter<"EmailChange"> | string
  new_email?: Prisma.StringWithAggregatesFilter<"EmailChange"> | string
  link_token?: Prisma.StringWithAggregatesFilter<"EmailChange"> | string
  otp_code?: Prisma.StringWithAggregatesFilter<"EmailChange"> | string
  attempts?: Prisma.IntWithAggregatesFilter<"EmailChange"> | number
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"EmailChange"> | Date | string
  used_at?: Prisma.DateTimeNullableWithAggregatesFilter<"EmailChange"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"EmailChange"> | Date | string
}

export type EmailChangeCreateInput = {
  id?: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutEmail_changesInput
}

export type EmailChangeUncheckedCreateInput = {
  id?: string
  user_id: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
}

export type EmailChangeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutEmail_changesNestedInput
}

export type EmailChangeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailChangeCreateManyInput = {
  id?: string
  user_id: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
}

export type EmailChangeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailChangeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailChangeListRelationFilter = {
  every?: Prisma.EmailChangeWhereInput
  some?: Prisma.EmailChangeWhereInput
  none?: Prisma.EmailChangeWhereInput
}

export type EmailChangeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmailChangeOrderByRelevanceInput = {
  fields: Prisma.EmailChangeOrderByRelevanceFieldEnum | Prisma.EmailChangeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type EmailChangeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  new_email?: Prisma.SortOrder
  link_token?: Prisma.SortOrder
  otp_code?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  used_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type EmailChangeAvgOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
}

export type EmailChangeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  new_email?: Prisma.SortOrder
  link_token?: Prisma.SortOrder
  otp_code?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  used_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type EmailChangeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  new_email?: Prisma.SortOrder
  link_token?: Prisma.SortOrder
  otp_code?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  used_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type EmailChangeSumOrderByAggregateInput = {
  attempts?: Prisma.SortOrder
}

export type EmailChangeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput> | Prisma.EmailChangeCreateWithoutUserInput[] | Prisma.EmailChangeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailChangeCreateOrConnectWithoutUserInput | Prisma.EmailChangeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmailChangeCreateManyUserInputEnvelope
  connect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
}

export type EmailChangeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput> | Prisma.EmailChangeCreateWithoutUserInput[] | Prisma.EmailChangeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailChangeCreateOrConnectWithoutUserInput | Prisma.EmailChangeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmailChangeCreateManyUserInputEnvelope
  connect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
}

export type EmailChangeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput> | Prisma.EmailChangeCreateWithoutUserInput[] | Prisma.EmailChangeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailChangeCreateOrConnectWithoutUserInput | Prisma.EmailChangeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmailChangeUpsertWithWhereUniqueWithoutUserInput | Prisma.EmailChangeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmailChangeCreateManyUserInputEnvelope
  set?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  disconnect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  delete?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  connect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  update?: Prisma.EmailChangeUpdateWithWhereUniqueWithoutUserInput | Prisma.EmailChangeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmailChangeUpdateManyWithWhereWithoutUserInput | Prisma.EmailChangeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmailChangeScalarWhereInput | Prisma.EmailChangeScalarWhereInput[]
}

export type EmailChangeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput> | Prisma.EmailChangeCreateWithoutUserInput[] | Prisma.EmailChangeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailChangeCreateOrConnectWithoutUserInput | Prisma.EmailChangeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmailChangeUpsertWithWhereUniqueWithoutUserInput | Prisma.EmailChangeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmailChangeCreateManyUserInputEnvelope
  set?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  disconnect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  delete?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  connect?: Prisma.EmailChangeWhereUniqueInput | Prisma.EmailChangeWhereUniqueInput[]
  update?: Prisma.EmailChangeUpdateWithWhereUniqueWithoutUserInput | Prisma.EmailChangeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmailChangeUpdateManyWithWhereWithoutUserInput | Prisma.EmailChangeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmailChangeScalarWhereInput | Prisma.EmailChangeScalarWhereInput[]
}

export type EmailChangeCreateWithoutUserInput = {
  id?: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
}

export type EmailChangeUncheckedCreateWithoutUserInput = {
  id?: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
}

export type EmailChangeCreateOrConnectWithoutUserInput = {
  where: Prisma.EmailChangeWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput>
}

export type EmailChangeCreateManyUserInputEnvelope = {
  data: Prisma.EmailChangeCreateManyUserInput | Prisma.EmailChangeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type EmailChangeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmailChangeWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailChangeUpdateWithoutUserInput, Prisma.EmailChangeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EmailChangeCreateWithoutUserInput, Prisma.EmailChangeUncheckedCreateWithoutUserInput>
}

export type EmailChangeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmailChangeWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailChangeUpdateWithoutUserInput, Prisma.EmailChangeUncheckedUpdateWithoutUserInput>
}

export type EmailChangeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EmailChangeScalarWhereInput
  data: Prisma.XOR<Prisma.EmailChangeUpdateManyMutationInput, Prisma.EmailChangeUncheckedUpdateManyWithoutUserInput>
}

export type EmailChangeScalarWhereInput = {
  AND?: Prisma.EmailChangeScalarWhereInput | Prisma.EmailChangeScalarWhereInput[]
  OR?: Prisma.EmailChangeScalarWhereInput[]
  NOT?: Prisma.EmailChangeScalarWhereInput | Prisma.EmailChangeScalarWhereInput[]
  id?: Prisma.StringFilter<"EmailChange"> | string
  user_id?: Prisma.StringFilter<"EmailChange"> | string
  new_email?: Prisma.StringFilter<"EmailChange"> | string
  link_token?: Prisma.StringFilter<"EmailChange"> | string
  otp_code?: Prisma.StringFilter<"EmailChange"> | string
  attempts?: Prisma.IntFilter<"EmailChange"> | number
  expires_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
  used_at?: Prisma.DateTimeNullableFilter<"EmailChange"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"EmailChange"> | Date | string
}

export type EmailChangeCreateManyUserInput = {
  id?: string
  new_email: string
  link_token?: string
  otp_code: string
  attempts?: number
  expires_at: Date | string
  used_at?: Date | string | null
  created_at?: Date | string
}

export type EmailChangeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailChangeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailChangeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  new_email?: Prisma.StringFieldUpdateOperationsInput | string
  link_token?: Prisma.StringFieldUpdateOperationsInput | string
  otp_code?: Prisma.StringFieldUpdateOperationsInput | string
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EmailChangeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  new_email?: boolean
  link_token?: boolean
  otp_code?: boolean
  attempts?: boolean
  expires_at?: boolean
  used_at?: boolean
  created_at?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailChange"]>



export type EmailChangeSelectScalar = {
  id?: boolean
  user_id?: boolean
  new_email?: boolean
  link_token?: boolean
  otp_code?: boolean
  attempts?: boolean
  expires_at?: boolean
  used_at?: boolean
  created_at?: boolean
}

export type EmailChangeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "new_email" | "link_token" | "otp_code" | "attempts" | "expires_at" | "used_at" | "created_at", ExtArgs["result"]["emailChange"]>
export type EmailChangeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $EmailChangePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmailChange"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    new_email: string
    link_token: string
    otp_code: string
    attempts: number
    expires_at: Date
    used_at: Date | null
    created_at: Date
  }, ExtArgs["result"]["emailChange"]>
  composites: {}
}

export type EmailChangeGetPayload<S extends boolean | null | undefined | EmailChangeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmailChangePayload, S>

export type EmailChangeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmailChangeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmailChangeCountAggregateInputType | true
  }

export interface EmailChangeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmailChange'], meta: { name: 'EmailChange' } }
  /**
   * Find zero or one EmailChange that matches the filter.
   * @param {EmailChangeFindUniqueArgs} args - Arguments to find a EmailChange
   * @example
   * // Get one EmailChange
   * const emailChange = await prisma.emailChange.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmailChangeFindUniqueArgs>(args: Prisma.SelectSubset<T, EmailChangeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmailChange that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmailChangeFindUniqueOrThrowArgs} args - Arguments to find a EmailChange
   * @example
   * // Get one EmailChange
   * const emailChange = await prisma.emailChange.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmailChangeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmailChangeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailChange that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeFindFirstArgs} args - Arguments to find a EmailChange
   * @example
   * // Get one EmailChange
   * const emailChange = await prisma.emailChange.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmailChangeFindFirstArgs>(args?: Prisma.SelectSubset<T, EmailChangeFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailChange that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeFindFirstOrThrowArgs} args - Arguments to find a EmailChange
   * @example
   * // Get one EmailChange
   * const emailChange = await prisma.emailChange.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmailChangeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmailChangeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmailChanges that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmailChanges
   * const emailChanges = await prisma.emailChange.findMany()
   * 
   * // Get first 10 EmailChanges
   * const emailChanges = await prisma.emailChange.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emailChangeWithIdOnly = await prisma.emailChange.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmailChangeFindManyArgs>(args?: Prisma.SelectSubset<T, EmailChangeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmailChange.
   * @param {EmailChangeCreateArgs} args - Arguments to create a EmailChange.
   * @example
   * // Create one EmailChange
   * const EmailChange = await prisma.emailChange.create({
   *   data: {
   *     // ... data to create a EmailChange
   *   }
   * })
   * 
   */
  create<T extends EmailChangeCreateArgs>(args: Prisma.SelectSubset<T, EmailChangeCreateArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmailChanges.
   * @param {EmailChangeCreateManyArgs} args - Arguments to create many EmailChanges.
   * @example
   * // Create many EmailChanges
   * const emailChange = await prisma.emailChange.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmailChangeCreateManyArgs>(args?: Prisma.SelectSubset<T, EmailChangeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a EmailChange.
   * @param {EmailChangeDeleteArgs} args - Arguments to delete one EmailChange.
   * @example
   * // Delete one EmailChange
   * const EmailChange = await prisma.emailChange.delete({
   *   where: {
   *     // ... filter to delete one EmailChange
   *   }
   * })
   * 
   */
  delete<T extends EmailChangeDeleteArgs>(args: Prisma.SelectSubset<T, EmailChangeDeleteArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmailChange.
   * @param {EmailChangeUpdateArgs} args - Arguments to update one EmailChange.
   * @example
   * // Update one EmailChange
   * const emailChange = await prisma.emailChange.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmailChangeUpdateArgs>(args: Prisma.SelectSubset<T, EmailChangeUpdateArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmailChanges.
   * @param {EmailChangeDeleteManyArgs} args - Arguments to filter EmailChanges to delete.
   * @example
   * // Delete a few EmailChanges
   * const { count } = await prisma.emailChange.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmailChangeDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmailChangeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailChanges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmailChanges
   * const emailChange = await prisma.emailChange.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmailChangeUpdateManyArgs>(args: Prisma.SelectSubset<T, EmailChangeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one EmailChange.
   * @param {EmailChangeUpsertArgs} args - Arguments to update or create a EmailChange.
   * @example
   * // Update or create a EmailChange
   * const emailChange = await prisma.emailChange.upsert({
   *   create: {
   *     // ... data to create a EmailChange
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmailChange we want to update
   *   }
   * })
   */
  upsert<T extends EmailChangeUpsertArgs>(args: Prisma.SelectSubset<T, EmailChangeUpsertArgs<ExtArgs>>): Prisma.Prisma__EmailChangeClient<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmailChanges.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeCountArgs} args - Arguments to filter EmailChanges to count.
   * @example
   * // Count the number of EmailChanges
   * const count = await prisma.emailChange.count({
   *   where: {
   *     // ... the filter for the EmailChanges we want to count
   *   }
   * })
  **/
  count<T extends EmailChangeCountArgs>(
    args?: Prisma.Subset<T, EmailChangeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmailChangeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmailChange.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmailChangeAggregateArgs>(args: Prisma.Subset<T, EmailChangeAggregateArgs>): Prisma.PrismaPromise<GetEmailChangeAggregateType<T>>

  /**
   * Group by EmailChange.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailChangeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmailChangeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmailChangeGroupByArgs['orderBy'] }
      : { orderBy?: EmailChangeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmailChangeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmailChangeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmailChange model
 */
readonly fields: EmailChangeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmailChange.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmailChangeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmailChange model
 */
export interface EmailChangeFieldRefs {
  readonly id: Prisma.FieldRef<"EmailChange", 'String'>
  readonly user_id: Prisma.FieldRef<"EmailChange", 'String'>
  readonly new_email: Prisma.FieldRef<"EmailChange", 'String'>
  readonly link_token: Prisma.FieldRef<"EmailChange", 'String'>
  readonly otp_code: Prisma.FieldRef<"EmailChange", 'String'>
  readonly attempts: Prisma.FieldRef<"EmailChange", 'Int'>
  readonly expires_at: Prisma.FieldRef<"EmailChange", 'DateTime'>
  readonly used_at: Prisma.FieldRef<"EmailChange", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"EmailChange", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EmailChange findUnique
 */
export type EmailChangeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter, which EmailChange to fetch.
   */
  where: Prisma.EmailChangeWhereUniqueInput
}

/**
 * EmailChange findUniqueOrThrow
 */
export type EmailChangeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter, which EmailChange to fetch.
   */
  where: Prisma.EmailChangeWhereUniqueInput
}

/**
 * EmailChange findFirst
 */
export type EmailChangeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter, which EmailChange to fetch.
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailChanges to fetch.
   */
  orderBy?: Prisma.EmailChangeOrderByWithRelationInput | Prisma.EmailChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailChanges.
   */
  cursor?: Prisma.EmailChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailChanges.
   */
  distinct?: Prisma.EmailChangeScalarFieldEnum | Prisma.EmailChangeScalarFieldEnum[]
}

/**
 * EmailChange findFirstOrThrow
 */
export type EmailChangeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter, which EmailChange to fetch.
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailChanges to fetch.
   */
  orderBy?: Prisma.EmailChangeOrderByWithRelationInput | Prisma.EmailChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailChanges.
   */
  cursor?: Prisma.EmailChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailChanges.
   */
  distinct?: Prisma.EmailChangeScalarFieldEnum | Prisma.EmailChangeScalarFieldEnum[]
}

/**
 * EmailChange findMany
 */
export type EmailChangeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter, which EmailChanges to fetch.
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailChanges to fetch.
   */
  orderBy?: Prisma.EmailChangeOrderByWithRelationInput | Prisma.EmailChangeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmailChanges.
   */
  cursor?: Prisma.EmailChangeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailChanges from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailChanges.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailChanges.
   */
  distinct?: Prisma.EmailChangeScalarFieldEnum | Prisma.EmailChangeScalarFieldEnum[]
}

/**
 * EmailChange create
 */
export type EmailChangeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * The data needed to create a EmailChange.
   */
  data: Prisma.XOR<Prisma.EmailChangeCreateInput, Prisma.EmailChangeUncheckedCreateInput>
}

/**
 * EmailChange createMany
 */
export type EmailChangeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmailChanges.
   */
  data: Prisma.EmailChangeCreateManyInput | Prisma.EmailChangeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EmailChange update
 */
export type EmailChangeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * The data needed to update a EmailChange.
   */
  data: Prisma.XOR<Prisma.EmailChangeUpdateInput, Prisma.EmailChangeUncheckedUpdateInput>
  /**
   * Choose, which EmailChange to update.
   */
  where: Prisma.EmailChangeWhereUniqueInput
}

/**
 * EmailChange updateMany
 */
export type EmailChangeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmailChanges.
   */
  data: Prisma.XOR<Prisma.EmailChangeUpdateManyMutationInput, Prisma.EmailChangeUncheckedUpdateManyInput>
  /**
   * Filter which EmailChanges to update
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * Limit how many EmailChanges to update.
   */
  limit?: number
}

/**
 * EmailChange upsert
 */
export type EmailChangeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * The filter to search for the EmailChange to update in case it exists.
   */
  where: Prisma.EmailChangeWhereUniqueInput
  /**
   * In case the EmailChange found by the `where` argument doesn't exist, create a new EmailChange with this data.
   */
  create: Prisma.XOR<Prisma.EmailChangeCreateInput, Prisma.EmailChangeUncheckedCreateInput>
  /**
   * In case the EmailChange was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmailChangeUpdateInput, Prisma.EmailChangeUncheckedUpdateInput>
}

/**
 * EmailChange delete
 */
export type EmailChangeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  /**
   * Filter which EmailChange to delete.
   */
  where: Prisma.EmailChangeWhereUniqueInput
}

/**
 * EmailChange deleteMany
 */
export type EmailChangeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailChanges to delete
   */
  where?: Prisma.EmailChangeWhereInput
  /**
   * Limit how many EmailChanges to delete.
   */
  limit?: number
}

/**
 * EmailChange without action
 */
export type EmailChangeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
}
