
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RevokedToken` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RevokedToken
 * 
 */
export type RevokedTokenModel = runtime.Types.Result.DefaultSelection<Prisma.$RevokedTokenPayload>

export type AggregateRevokedToken = {
  _count: RevokedTokenCountAggregateOutputType | null
  _min: RevokedTokenMinAggregateOutputType | null
  _max: RevokedTokenMaxAggregateOutputType | null
}

export type RevokedTokenMinAggregateOutputType = {
  jti: string | null
  expires_at: Date | null
  created_at: Date | null
}

export type RevokedTokenMaxAggregateOutputType = {
  jti: string | null
  expires_at: Date | null
  created_at: Date | null
}

export type RevokedTokenCountAggregateOutputType = {
  jti: number
  expires_at: number
  created_at: number
  _all: number
}


export type RevokedTokenMinAggregateInputType = {
  jti?: true
  expires_at?: true
  created_at?: true
}

export type RevokedTokenMaxAggregateInputType = {
  jti?: true
  expires_at?: true
  created_at?: true
}

export type RevokedTokenCountAggregateInputType = {
  jti?: true
  expires_at?: true
  created_at?: true
  _all?: true
}

export type RevokedTokenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevokedToken to aggregate.
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevokedTokens to fetch.
   */
  orderBy?: Prisma.RevokedTokenOrderByWithRelationInput | Prisma.RevokedTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RevokedTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevokedTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevokedTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RevokedTokens
  **/
  _count?: true | RevokedTokenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RevokedTokenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RevokedTokenMaxAggregateInputType
}

export type GetRevokedTokenAggregateType<T extends RevokedTokenAggregateArgs> = {
      [P in keyof T & keyof AggregateRevokedToken]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRevokedToken[P]>
    : Prisma.GetScalarType<T[P], AggregateRevokedToken[P]>
}




export type RevokedTokenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RevokedTokenWhereInput
  orderBy?: Prisma.RevokedTokenOrderByWithAggregationInput | Prisma.RevokedTokenOrderByWithAggregationInput[]
  by: Prisma.RevokedTokenScalarFieldEnum[] | Prisma.RevokedTokenScalarFieldEnum
  having?: Prisma.RevokedTokenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RevokedTokenCountAggregateInputType | true
  _min?: RevokedTokenMinAggregateInputType
  _max?: RevokedTokenMaxAggregateInputType
}

export type RevokedTokenGroupByOutputType = {
  jti: string
  expires_at: Date
  created_at: Date
  _count: RevokedTokenCountAggregateOutputType | null
  _min: RevokedTokenMinAggregateOutputType | null
  _max: RevokedTokenMaxAggregateOutputType | null
}

export type GetRevokedTokenGroupByPayload<T extends RevokedTokenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RevokedTokenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RevokedTokenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RevokedTokenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RevokedTokenGroupByOutputType[P]>
      }
    >
  >



export type RevokedTokenWhereInput = {
  AND?: Prisma.RevokedTokenWhereInput | Prisma.RevokedTokenWhereInput[]
  OR?: Prisma.RevokedTokenWhereInput[]
  NOT?: Prisma.RevokedTokenWhereInput | Prisma.RevokedTokenWhereInput[]
  jti?: Prisma.StringFilter<"RevokedToken"> | string
  expires_at?: Prisma.DateTimeFilter<"RevokedToken"> | Date | string
  created_at?: Prisma.DateTimeFilter<"RevokedToken"> | Date | string
}

export type RevokedTokenOrderByWithRelationInput = {
  jti?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _relevance?: Prisma.RevokedTokenOrderByRelevanceInput
}

export type RevokedTokenWhereUniqueInput = Prisma.AtLeast<{
  jti?: string
  AND?: Prisma.RevokedTokenWhereInput | Prisma.RevokedTokenWhereInput[]
  OR?: Prisma.RevokedTokenWhereInput[]
  NOT?: Prisma.RevokedTokenWhereInput | Prisma.RevokedTokenWhereInput[]
  expires_at?: Prisma.DateTimeFilter<"RevokedToken"> | Date | string
  created_at?: Prisma.DateTimeFilter<"RevokedToken"> | Date | string
}, "jti">

export type RevokedTokenOrderByWithAggregationInput = {
  jti?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.RevokedTokenCountOrderByAggregateInput
  _max?: Prisma.RevokedTokenMaxOrderByAggregateInput
  _min?: Prisma.RevokedTokenMinOrderByAggregateInput
}

export type RevokedTokenScalarWhereWithAggregatesInput = {
  AND?: Prisma.RevokedTokenScalarWhereWithAggregatesInput | Prisma.RevokedTokenScalarWhereWithAggregatesInput[]
  OR?: Prisma.RevokedTokenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RevokedTokenScalarWhereWithAggregatesInput | Prisma.RevokedTokenScalarWhereWithAggregatesInput[]
  jti?: Prisma.StringWithAggregatesFilter<"RevokedToken"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"RevokedToken"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"RevokedToken"> | Date | string
}

export type RevokedTokenCreateInput = {
  jti: string
  expires_at: Date | string
  created_at?: Date | string
}

export type RevokedTokenUncheckedCreateInput = {
  jti: string
  expires_at: Date | string
  created_at?: Date | string
}

export type RevokedTokenUpdateInput = {
  jti?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RevokedTokenUncheckedUpdateInput = {
  jti?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RevokedTokenCreateManyInput = {
  jti: string
  expires_at: Date | string
  created_at?: Date | string
}

export type RevokedTokenUpdateManyMutationInput = {
  jti?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RevokedTokenUncheckedUpdateManyInput = {
  jti?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RevokedTokenOrderByRelevanceInput = {
  fields: Prisma.RevokedTokenOrderByRelevanceFieldEnum | Prisma.RevokedTokenOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type RevokedTokenCountOrderByAggregateInput = {
  jti?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type RevokedTokenMaxOrderByAggregateInput = {
  jti?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type RevokedTokenMinOrderByAggregateInput = {
  jti?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}



export type RevokedTokenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  jti?: boolean
  expires_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["revokedToken"]>



export type RevokedTokenSelectScalar = {
  jti?: boolean
  expires_at?: boolean
  created_at?: boolean
}

export type RevokedTokenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"jti" | "expires_at" | "created_at", ExtArgs["result"]["revokedToken"]>

export type $RevokedTokenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RevokedToken"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    jti: string
    expires_at: Date
    created_at: Date
  }, ExtArgs["result"]["revokedToken"]>
  composites: {}
}

export type RevokedTokenGetPayload<S extends boolean | null | undefined | RevokedTokenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload, S>

export type RevokedTokenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RevokedTokenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RevokedTokenCountAggregateInputType | true
  }

export interface RevokedTokenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RevokedToken'], meta: { name: 'RevokedToken' } }
  /**
   * Find zero or one RevokedToken that matches the filter.
   * @param {RevokedTokenFindUniqueArgs} args - Arguments to find a RevokedToken
   * @example
   * // Get one RevokedToken
   * const revokedToken = await prisma.revokedToken.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RevokedTokenFindUniqueArgs>(args: Prisma.SelectSubset<T, RevokedTokenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RevokedToken that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RevokedTokenFindUniqueOrThrowArgs} args - Arguments to find a RevokedToken
   * @example
   * // Get one RevokedToken
   * const revokedToken = await prisma.revokedToken.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RevokedTokenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RevokedTokenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevokedToken that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenFindFirstArgs} args - Arguments to find a RevokedToken
   * @example
   * // Get one RevokedToken
   * const revokedToken = await prisma.revokedToken.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RevokedTokenFindFirstArgs>(args?: Prisma.SelectSubset<T, RevokedTokenFindFirstArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RevokedToken that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenFindFirstOrThrowArgs} args - Arguments to find a RevokedToken
   * @example
   * // Get one RevokedToken
   * const revokedToken = await prisma.revokedToken.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RevokedTokenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RevokedTokenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RevokedTokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RevokedTokens
   * const revokedTokens = await prisma.revokedToken.findMany()
   * 
   * // Get first 10 RevokedTokens
   * const revokedTokens = await prisma.revokedToken.findMany({ take: 10 })
   * 
   * // Only select the `jti`
   * const revokedTokenWithJtiOnly = await prisma.revokedToken.findMany({ select: { jti: true } })
   * 
   */
  findMany<T extends RevokedTokenFindManyArgs>(args?: Prisma.SelectSubset<T, RevokedTokenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RevokedToken.
   * @param {RevokedTokenCreateArgs} args - Arguments to create a RevokedToken.
   * @example
   * // Create one RevokedToken
   * const RevokedToken = await prisma.revokedToken.create({
   *   data: {
   *     // ... data to create a RevokedToken
   *   }
   * })
   * 
   */
  create<T extends RevokedTokenCreateArgs>(args: Prisma.SelectSubset<T, RevokedTokenCreateArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RevokedTokens.
   * @param {RevokedTokenCreateManyArgs} args - Arguments to create many RevokedTokens.
   * @example
   * // Create many RevokedTokens
   * const revokedToken = await prisma.revokedToken.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RevokedTokenCreateManyArgs>(args?: Prisma.SelectSubset<T, RevokedTokenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a RevokedToken.
   * @param {RevokedTokenDeleteArgs} args - Arguments to delete one RevokedToken.
   * @example
   * // Delete one RevokedToken
   * const RevokedToken = await prisma.revokedToken.delete({
   *   where: {
   *     // ... filter to delete one RevokedToken
   *   }
   * })
   * 
   */
  delete<T extends RevokedTokenDeleteArgs>(args: Prisma.SelectSubset<T, RevokedTokenDeleteArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RevokedToken.
   * @param {RevokedTokenUpdateArgs} args - Arguments to update one RevokedToken.
   * @example
   * // Update one RevokedToken
   * const revokedToken = await prisma.revokedToken.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RevokedTokenUpdateArgs>(args: Prisma.SelectSubset<T, RevokedTokenUpdateArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RevokedTokens.
   * @param {RevokedTokenDeleteManyArgs} args - Arguments to filter RevokedTokens to delete.
   * @example
   * // Delete a few RevokedTokens
   * const { count } = await prisma.revokedToken.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RevokedTokenDeleteManyArgs>(args?: Prisma.SelectSubset<T, RevokedTokenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RevokedTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RevokedTokens
   * const revokedToken = await prisma.revokedToken.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RevokedTokenUpdateManyArgs>(args: Prisma.SelectSubset<T, RevokedTokenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one RevokedToken.
   * @param {RevokedTokenUpsertArgs} args - Arguments to update or create a RevokedToken.
   * @example
   * // Update or create a RevokedToken
   * const revokedToken = await prisma.revokedToken.upsert({
   *   create: {
   *     // ... data to create a RevokedToken
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RevokedToken we want to update
   *   }
   * })
   */
  upsert<T extends RevokedTokenUpsertArgs>(args: Prisma.SelectSubset<T, RevokedTokenUpsertArgs<ExtArgs>>): Prisma.Prisma__RevokedTokenClient<runtime.Types.Result.GetResult<Prisma.$RevokedTokenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RevokedTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenCountArgs} args - Arguments to filter RevokedTokens to count.
   * @example
   * // Count the number of RevokedTokens
   * const count = await prisma.revokedToken.count({
   *   where: {
   *     // ... the filter for the RevokedTokens we want to count
   *   }
   * })
  **/
  count<T extends RevokedTokenCountArgs>(
    args?: Prisma.Subset<T, RevokedTokenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RevokedTokenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RevokedToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RevokedTokenAggregateArgs>(args: Prisma.Subset<T, RevokedTokenAggregateArgs>): Prisma.PrismaPromise<GetRevokedTokenAggregateType<T>>

  /**
   * Group by RevokedToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RevokedTokenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RevokedTokenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RevokedTokenGroupByArgs['orderBy'] }
      : { orderBy?: RevokedTokenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RevokedTokenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRevokedTokenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RevokedToken model
 */
readonly fields: RevokedTokenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RevokedToken.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RevokedTokenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RevokedToken model
 */
export interface RevokedTokenFieldRefs {
  readonly jti: Prisma.FieldRef<"RevokedToken", 'String'>
  readonly expires_at: Prisma.FieldRef<"RevokedToken", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"RevokedToken", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RevokedToken findUnique
 */
export type RevokedTokenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter, which RevokedToken to fetch.
   */
  where: Prisma.RevokedTokenWhereUniqueInput
}

/**
 * RevokedToken findUniqueOrThrow
 */
export type RevokedTokenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter, which RevokedToken to fetch.
   */
  where: Prisma.RevokedTokenWhereUniqueInput
}

/**
 * RevokedToken findFirst
 */
export type RevokedTokenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter, which RevokedToken to fetch.
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevokedTokens to fetch.
   */
  orderBy?: Prisma.RevokedTokenOrderByWithRelationInput | Prisma.RevokedTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevokedTokens.
   */
  cursor?: Prisma.RevokedTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevokedTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevokedTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevokedTokens.
   */
  distinct?: Prisma.RevokedTokenScalarFieldEnum | Prisma.RevokedTokenScalarFieldEnum[]
}

/**
 * RevokedToken findFirstOrThrow
 */
export type RevokedTokenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter, which RevokedToken to fetch.
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevokedTokens to fetch.
   */
  orderBy?: Prisma.RevokedTokenOrderByWithRelationInput | Prisma.RevokedTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RevokedTokens.
   */
  cursor?: Prisma.RevokedTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevokedTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevokedTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevokedTokens.
   */
  distinct?: Prisma.RevokedTokenScalarFieldEnum | Prisma.RevokedTokenScalarFieldEnum[]
}

/**
 * RevokedToken findMany
 */
export type RevokedTokenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter, which RevokedTokens to fetch.
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RevokedTokens to fetch.
   */
  orderBy?: Prisma.RevokedTokenOrderByWithRelationInput | Prisma.RevokedTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RevokedTokens.
   */
  cursor?: Prisma.RevokedTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RevokedTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RevokedTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RevokedTokens.
   */
  distinct?: Prisma.RevokedTokenScalarFieldEnum | Prisma.RevokedTokenScalarFieldEnum[]
}

/**
 * RevokedToken create
 */
export type RevokedTokenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * The data needed to create a RevokedToken.
   */
  data: Prisma.XOR<Prisma.RevokedTokenCreateInput, Prisma.RevokedTokenUncheckedCreateInput>
}

/**
 * RevokedToken createMany
 */
export type RevokedTokenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RevokedTokens.
   */
  data: Prisma.RevokedTokenCreateManyInput | Prisma.RevokedTokenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RevokedToken update
 */
export type RevokedTokenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * The data needed to update a RevokedToken.
   */
  data: Prisma.XOR<Prisma.RevokedTokenUpdateInput, Prisma.RevokedTokenUncheckedUpdateInput>
  /**
   * Choose, which RevokedToken to update.
   */
  where: Prisma.RevokedTokenWhereUniqueInput
}

/**
 * RevokedToken updateMany
 */
export type RevokedTokenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RevokedTokens.
   */
  data: Prisma.XOR<Prisma.RevokedTokenUpdateManyMutationInput, Prisma.RevokedTokenUncheckedUpdateManyInput>
  /**
   * Filter which RevokedTokens to update
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * Limit how many RevokedTokens to update.
   */
  limit?: number
}

/**
 * RevokedToken upsert
 */
export type RevokedTokenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * The filter to search for the RevokedToken to update in case it exists.
   */
  where: Prisma.RevokedTokenWhereUniqueInput
  /**
   * In case the RevokedToken found by the `where` argument doesn't exist, create a new RevokedToken with this data.
   */
  create: Prisma.XOR<Prisma.RevokedTokenCreateInput, Prisma.RevokedTokenUncheckedCreateInput>
  /**
   * In case the RevokedToken was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RevokedTokenUpdateInput, Prisma.RevokedTokenUncheckedUpdateInput>
}

/**
 * RevokedToken delete
 */
export type RevokedTokenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
  /**
   * Filter which RevokedToken to delete.
   */
  where: Prisma.RevokedTokenWhereUniqueInput
}

/**
 * RevokedToken deleteMany
 */
export type RevokedTokenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RevokedTokens to delete
   */
  where?: Prisma.RevokedTokenWhereInput
  /**
   * Limit how many RevokedTokens to delete.
   */
  limit?: number
}

/**
 * RevokedToken without action
 */
export type RevokedTokenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RevokedToken
   */
  select?: Prisma.RevokedTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RevokedToken
   */
  omit?: Prisma.RevokedTokenOmit<ExtArgs> | null
}
