
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  username: string | null
  email: string | null
  password_hash: string | null
  role: $Enums.Role | null
  is_verified: boolean | null
  created_at: Date | null
  password_changed_at: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  username: string | null
  email: string | null
  password_hash: string | null
  role: $Enums.Role | null
  is_verified: boolean | null
  created_at: Date | null
  password_changed_at: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  username: number
  email: number
  password_hash: number
  role: number
  is_verified: number
  created_at: number
  password_changed_at: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password_hash?: true
  role?: true
  is_verified?: true
  created_at?: true
  password_changed_at?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password_hash?: true
  role?: true
  is_verified?: true
  created_at?: true
  password_changed_at?: true
}

export type UserCountAggregateInputType = {
  id?: true
  username?: true
  email?: true
  password_hash?: true
  role?: true
  is_verified?: true
  created_at?: true
  password_changed_at?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  username: string
  email: string
  password_hash: string
  role: $Enums.Role
  is_verified: boolean
  created_at: Date
  password_changed_at: Date | null
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  username?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringFilter<"User"> | string
  password_hash?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  is_verified?: Prisma.BoolFilter<"User"> | boolean
  created_at?: Prisma.DateTimeFilter<"User"> | Date | string
  password_changed_at?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  checkIns?: Prisma.CheckInListRelationFilter
  email_verifications?: Prisma.EmailVerificationListRelationFilter
  password_resets?: Prisma.PasswordResetListRelationFilter
  email_changes?: Prisma.EmailChangeListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  password_changed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  checkIns?: Prisma.CheckInOrderByRelationAggregateInput
  email_verifications?: Prisma.EmailVerificationOrderByRelationAggregateInput
  password_resets?: Prisma.PasswordResetOrderByRelationAggregateInput
  email_changes?: Prisma.EmailChangeOrderByRelationAggregateInput
  _relevance?: Prisma.UserOrderByRelevanceInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  username?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  password_hash?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  is_verified?: Prisma.BoolFilter<"User"> | boolean
  created_at?: Prisma.DateTimeFilter<"User"> | Date | string
  password_changed_at?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  checkIns?: Prisma.CheckInListRelationFilter
  email_verifications?: Prisma.EmailVerificationListRelationFilter
  password_resets?: Prisma.PasswordResetListRelationFilter
  email_changes?: Prisma.EmailChangeListRelationFilter
}, "id" | "username" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  password_changed_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  username?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  password_hash?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  is_verified?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  password_changed_at?: Prisma.DateTimeNullableWithAggregatesFilter<"User"> | Date | string | null
}

export type UserCreateInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInUncheckedCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationUncheckedCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetUncheckedCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUncheckedUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUncheckedUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUncheckedUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type UserOrderByRelevanceInput = {
  fields: Prisma.UserOrderByRelevanceFieldEnum | Prisma.UserOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  password_changed_at?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  password_changed_at?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  role?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  password_changed_at?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type UserCreateNestedOneWithoutCheckInsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCheckInsInput, Prisma.UserUncheckedCreateWithoutCheckInsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCheckInsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCheckInsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCheckInsInput, Prisma.UserUncheckedCreateWithoutCheckInsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCheckInsInput
  upsert?: Prisma.UserUpsertWithoutCheckInsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCheckInsInput, Prisma.UserUpdateWithoutCheckInsInput>, Prisma.UserUncheckedUpdateWithoutCheckInsInput>
}

export type UserCreateNestedOneWithoutEmail_verificationsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEmail_verificationsInput, Prisma.UserUncheckedCreateWithoutEmail_verificationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEmail_verificationsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutEmail_verificationsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEmail_verificationsInput, Prisma.UserUncheckedCreateWithoutEmail_verificationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEmail_verificationsInput
  upsert?: Prisma.UserUpsertWithoutEmail_verificationsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutEmail_verificationsInput, Prisma.UserUpdateWithoutEmail_verificationsInput>, Prisma.UserUncheckedUpdateWithoutEmail_verificationsInput>
}

export type UserCreateNestedOneWithoutEmail_changesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEmail_changesInput, Prisma.UserUncheckedCreateWithoutEmail_changesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEmail_changesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutEmail_changesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutEmail_changesInput, Prisma.UserUncheckedCreateWithoutEmail_changesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutEmail_changesInput
  upsert?: Prisma.UserUpsertWithoutEmail_changesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutEmail_changesInput, Prisma.UserUpdateWithoutEmail_changesInput>, Prisma.UserUncheckedUpdateWithoutEmail_changesInput>
}

export type UserCreateNestedOneWithoutPassword_resetsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPassword_resetsInput, Prisma.UserUncheckedCreateWithoutPassword_resetsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPassword_resetsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutPassword_resetsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutPassword_resetsInput, Prisma.UserUncheckedCreateWithoutPassword_resetsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutPassword_resetsInput
  upsert?: Prisma.UserUpsertWithoutPassword_resetsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutPassword_resetsInput, Prisma.UserUpdateWithoutPassword_resetsInput>, Prisma.UserUncheckedUpdateWithoutPassword_resetsInput>
}

export type UserCreateWithoutCheckInsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  email_verifications?: Prisma.EmailVerificationCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCheckInsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  email_verifications?: Prisma.EmailVerificationUncheckedCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetUncheckedCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCheckInsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCheckInsInput, Prisma.UserUncheckedCreateWithoutCheckInsInput>
}

export type UserUpsertWithoutCheckInsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCheckInsInput, Prisma.UserUncheckedUpdateWithoutCheckInsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCheckInsInput, Prisma.UserUncheckedCreateWithoutCheckInsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCheckInsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCheckInsInput, Prisma.UserUncheckedUpdateWithoutCheckInsInput>
}

export type UserUpdateWithoutCheckInsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  email_verifications?: Prisma.EmailVerificationUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCheckInsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  email_verifications?: Prisma.EmailVerificationUncheckedUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUncheckedUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutEmail_verificationsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutEmail_verificationsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInUncheckedCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetUncheckedCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutEmail_verificationsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutEmail_verificationsInput, Prisma.UserUncheckedCreateWithoutEmail_verificationsInput>
}

export type UserUpsertWithoutEmail_verificationsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutEmail_verificationsInput, Prisma.UserUncheckedUpdateWithoutEmail_verificationsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutEmail_verificationsInput, Prisma.UserUncheckedCreateWithoutEmail_verificationsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutEmail_verificationsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutEmail_verificationsInput, Prisma.UserUncheckedUpdateWithoutEmail_verificationsInput>
}

export type UserUpdateWithoutEmail_verificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutEmail_verificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUncheckedUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUncheckedUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutEmail_changesInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutEmail_changesInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInUncheckedCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationUncheckedCreateNestedManyWithoutUserInput
  password_resets?: Prisma.PasswordResetUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutEmail_changesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutEmail_changesInput, Prisma.UserUncheckedCreateWithoutEmail_changesInput>
}

export type UserUpsertWithoutEmail_changesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutEmail_changesInput, Prisma.UserUncheckedUpdateWithoutEmail_changesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutEmail_changesInput, Prisma.UserUncheckedCreateWithoutEmail_changesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutEmail_changesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutEmail_changesInput, Prisma.UserUncheckedUpdateWithoutEmail_changesInput>
}

export type UserUpdateWithoutEmail_changesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutEmail_changesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUncheckedUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUncheckedUpdateManyWithoutUserNestedInput
  password_resets?: Prisma.PasswordResetUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutPassword_resetsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutPassword_resetsInput = {
  id?: string
  username: string
  email: string
  password_hash: string
  role?: $Enums.Role
  is_verified?: boolean
  created_at?: Date | string
  password_changed_at?: Date | string | null
  checkIns?: Prisma.CheckInUncheckedCreateNestedManyWithoutUserInput
  email_verifications?: Prisma.EmailVerificationUncheckedCreateNestedManyWithoutUserInput
  email_changes?: Prisma.EmailChangeUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutPassword_resetsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutPassword_resetsInput, Prisma.UserUncheckedCreateWithoutPassword_resetsInput>
}

export type UserUpsertWithoutPassword_resetsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutPassword_resetsInput, Prisma.UserUncheckedUpdateWithoutPassword_resetsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutPassword_resetsInput, Prisma.UserUncheckedCreateWithoutPassword_resetsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutPassword_resetsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutPassword_resetsInput, Prisma.UserUncheckedUpdateWithoutPassword_resetsInput>
}

export type UserUpdateWithoutPassword_resetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutPassword_resetsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  password_changed_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  checkIns?: Prisma.CheckInUncheckedUpdateManyWithoutUserNestedInput
  email_verifications?: Prisma.EmailVerificationUncheckedUpdateManyWithoutUserNestedInput
  email_changes?: Prisma.EmailChangeUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  checkIns: number
  email_verifications: number
  password_resets: number
  email_changes: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checkIns?: boolean | UserCountOutputTypeCountCheckInsArgs
  email_verifications?: boolean | UserCountOutputTypeCountEmail_verificationsArgs
  password_resets?: boolean | UserCountOutputTypeCountPassword_resetsArgs
  email_changes?: boolean | UserCountOutputTypeCountEmail_changesArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCheckInsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckInWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountEmail_verificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailVerificationWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountPassword_resetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PasswordResetWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountEmail_changesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailChangeWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  email?: boolean
  password_hash?: boolean
  role?: boolean
  is_verified?: boolean
  created_at?: boolean
  password_changed_at?: boolean
  checkIns?: boolean | Prisma.User$checkInsArgs<ExtArgs>
  email_verifications?: boolean | Prisma.User$email_verificationsArgs<ExtArgs>
  password_resets?: boolean | Prisma.User$password_resetsArgs<ExtArgs>
  email_changes?: boolean | Prisma.User$email_changesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>



export type UserSelectScalar = {
  id?: boolean
  username?: boolean
  email?: boolean
  password_hash?: boolean
  role?: boolean
  is_verified?: boolean
  created_at?: boolean
  password_changed_at?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "email" | "password_hash" | "role" | "is_verified" | "created_at" | "password_changed_at", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checkIns?: boolean | Prisma.User$checkInsArgs<ExtArgs>
  email_verifications?: boolean | Prisma.User$email_verificationsArgs<ExtArgs>
  password_resets?: boolean | Prisma.User$password_resetsArgs<ExtArgs>
  email_changes?: boolean | Prisma.User$email_changesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    checkIns: Prisma.$CheckInPayload<ExtArgs>[]
    email_verifications: Prisma.$EmailVerificationPayload<ExtArgs>[]
    password_resets: Prisma.$PasswordResetPayload<ExtArgs>[]
    email_changes: Prisma.$EmailChangePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string
    email: string
    password_hash: string
    role: $Enums.Role
    is_verified: boolean
    created_at: Date
    password_changed_at: Date | null
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  checkIns<T extends Prisma.User$checkInsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$checkInsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckInPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  email_verifications<T extends Prisma.User$email_verificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$email_verificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailVerificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  password_resets<T extends Prisma.User$password_resetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$password_resetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PasswordResetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  email_changes<T extends Prisma.User$email_changesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$email_changesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailChangePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly username: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly password_hash: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly is_verified: Prisma.FieldRef<"User", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"User", 'DateTime'>
  readonly password_changed_at: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.checkIns
 */
export type User$checkInsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckIn
   */
  select?: Prisma.CheckInSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckIn
   */
  omit?: Prisma.CheckInOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckInInclude<ExtArgs> | null
  where?: Prisma.CheckInWhereInput
  orderBy?: Prisma.CheckInOrderByWithRelationInput | Prisma.CheckInOrderByWithRelationInput[]
  cursor?: Prisma.CheckInWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CheckInScalarFieldEnum | Prisma.CheckInScalarFieldEnum[]
}

/**
 * User.email_verifications
 */
export type User$email_verificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailVerification
   */
  select?: Prisma.EmailVerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailVerification
   */
  omit?: Prisma.EmailVerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailVerificationInclude<ExtArgs> | null
  where?: Prisma.EmailVerificationWhereInput
  orderBy?: Prisma.EmailVerificationOrderByWithRelationInput | Prisma.EmailVerificationOrderByWithRelationInput[]
  cursor?: Prisma.EmailVerificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmailVerificationScalarFieldEnum | Prisma.EmailVerificationScalarFieldEnum[]
}

/**
 * User.password_resets
 */
export type User$password_resetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PasswordReset
   */
  select?: Prisma.PasswordResetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PasswordReset
   */
  omit?: Prisma.PasswordResetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PasswordResetInclude<ExtArgs> | null
  where?: Prisma.PasswordResetWhereInput
  orderBy?: Prisma.PasswordResetOrderByWithRelationInput | Prisma.PasswordResetOrderByWithRelationInput[]
  cursor?: Prisma.PasswordResetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PasswordResetScalarFieldEnum | Prisma.PasswordResetScalarFieldEnum[]
}

/**
 * User.email_changes
 */
export type User$email_changesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChange
   */
  select?: Prisma.EmailChangeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChange
   */
  omit?: Prisma.EmailChangeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChangeInclude<ExtArgs> | null
  where?: Prisma.EmailChangeWhereInput
  orderBy?: Prisma.EmailChangeOrderByWithRelationInput | Prisma.EmailChangeOrderByWithRelationInput[]
  cursor?: Prisma.EmailChangeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmailChangeScalarFieldEnum | Prisma.EmailChangeScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
